AWSTemplateFormatVersion: 2010-09-09
Outputs:
  APIGWURL:
    Value: https://${ClickLoggerAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/dev
  LambdaTable:
    Value:
      Ref: ClickLoggerTable
  S3BucketSecureURL:
    Description: Secure bucket description
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
  WebsiteURL:
    Description: Bucket description
    Value:
      Fn::GetAtt:
      - S3Bucket
      - WebsiteURL
Parameters:
  Environment:
    Type: String
Resources:
  BucketPolicy:
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Statement:
        - - Sid: ReadBucketS3Group
          - Principal: '*'
          - Effect: Allow
          - Action: s3:GetObject
          - Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: S3Bucket
                - /*
    Type: AWS::S3::BucketPolicy
  ClickLoggerAPI:
    Properties:
      DefinitionBody:
        info:
          title:
            Ref: AWS::StackName
        paths:
          /test:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ClickLoggerLambda.Arn}/invocations
        swagger: 2.0
      StageName:
        Fn::Sub: ${Environment}
    Type: AWS::Serverless::Api
  ClickLoggerLambda:
    Properties:
      CodeUri: s3://clicklogger-dev/fb4f14efaaf1c5a8bd5a188be3246ad3
      Environment:
        Variables:
          MyTableName:
            Ref: ClickLoggerTable
      Events:
        MyEndpoint:
          Properties:
            Method: get
            Path: /test
            RestApiId:
              Ref: ClickLoggerAPI
          Type: Api
      Handler: sample.lambda_handler
      MemorySize: 128
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonDynamoDBFullAccess
      Runtime: Python3.7
      Timeout: 30
    Type: AWS::Serverless::Function
  ClickLoggerTable:
    Properties:
      PrimaryKey:
        Name: correlationid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: clickloggerlambda-dev
    Type: AWS::Serverless::SimpleTable
  S3Bucket:
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: clicklogger-dev1
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
