AWSTemplateFormatVersion: 2010-09-09
Outputs:
  APIGWURL:
    Value: https://${ClickLoggerAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/dev
  LambdaTable:
    Value:
      Ref: ClickLoggerTable
  S3BucketSecureURL:
    Description: Secure bucket description
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
  WebsiteURL:
    Description: Bucket description
    Value:
      Fn::GetAtt:
      - S3Bucket
      - WebsiteURL
Parameters:
  Environment:
    Type: String
  HashKeyElementName:
    AllowedPattern: '[a-zA-Z0-9]'
    ConstraintDescription: Should be A-Z and 0-9
    Description: Name for the column
    MaxLength: '2048'
    MinLength: '1'
    Type: String
  HashKeyElementType:
    AllowedPattern: '[S|N]'
    ConstraintDescription: Should be a string or numeric
    Description: Type for the column
    MaxLength: '32'
    MinLength: '1'
    Type: String
Resources:
  BucketPolicy:
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Statement:
        - - Sid: ReadBucketS3Group
          - Principal: '*'
          - Effect: Allow
          - Action: s3:GetObject
          - Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: S3Bucket
                - /*
    Type: AWS::S3::BucketPolicy
  ClickLoggerAPI:
    Properties:
      DefinitionBody:
        info:
          title:
            ref: AWS::StackName
        paths:
          /dev:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ClickLoggerLambda.Arn}/invocations
        swagger: 2.0
    Type: AWS::Serverless::Api
  ClickLoggerLambda:
    Properties:
      CodeUri: s3://clicklogger-dev/fb4f14efaaf1c5a8bd5a188be3246ad3
      Handler: sample.lambda_handler
      MemorySize: 128
      Policies:
      - AWSLambdaBasicExecutionRold
      - AmazonDynamoDBFullAccess
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: Python3.7
      Timeout: 30
    Type: AWS::Serverless::Function
  ClickLoggerTable:
    Properties:
      AttributeDefinition:
        AttributeName:
          Ref: HashKeyElementName
        AttributeType:
          Ref: HashKeyElementType
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: clicklogger-dev
    Type: AWS::Serverless::SimpleTable
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:*
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: root
    Type: AWS::IAM::Role
  S3Bucket:
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: clicklogger-dev1
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
